# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.network :hostonly, "192.168.20.10"

  config.vm.provision :chef_solo do | chef |
    chef.add_recipe "liveblogging"
    chef.json = {
        :mysql => {
          :server_root_password => "liveblogging",
          :server_repl_password => "liveblogging",
          :server_debian_password => "liveblogging"
      }
    }
  end

  config.vm.share_folder "liveblogging", "/var/www/wordpress/wp-content/plugins/liveblogging", "../build"

end
